// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnD0AGQyuL88Kpv55jaT_eZL9heF5L0lw',
    appId: '1:633225811547:web:cedf010d0438485d50117e',
    messagingSenderId: '633225811547',
    projectId: 'blood-app-79712',
    authDomain: 'blood-app-79712.firebaseapp.com',
    storageBucket: 'blood-app-79712.appspot.com',
    measurementId: 'G-378Q3FHQD6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqbFbXhebDhbNj3ZPyaGzLKdm60Jg26UA',
    appId: '1:633225811547:android:ee103a365ecd9ac650117e',
    messagingSenderId: '633225811547',
    projectId: 'blood-app-79712',
    storageBucket: 'blood-app-79712.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXjzGsAP58SmUSAwwxjfBRsG204Q20anI',
    appId: '1:633225811547:ios:691bd1304c335dc450117e',
    messagingSenderId: '633225811547',
    projectId: 'blood-app-79712',
    storageBucket: 'blood-app-79712.appspot.com',
    iosBundleId: 'com.yourdomain.bloodApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXjzGsAP58SmUSAwwxjfBRsG204Q20anI',
    appId: '1:633225811547:ios:bb7e988da4facf6150117e',
    messagingSenderId: '633225811547',
    projectId: 'blood-app-79712',
    storageBucket: 'blood-app-79712.appspot.com',
    iosBundleId: 'com.yourdomain.bloodApp.RunnerTests',
  );
}
